### PR TITLE
README updated

### PR DESCRIPTION
**Pull request by Divya10**

### CODE REVIEW

**Comment by shubhamvashisht** [comment]
How about we leave this issue for students?
Under Documentation/Training.

**Comment by Divya10** [comment]
Yes we can do that as well.

**Comment by shubhamvashisht** [comment]
@divya10   Great. Add GCI label and also add it to tasks in Code-in dashboard.

**Comment by Divya10** [comment]
@shubhamvashisht I cannot add the label as I am not a contributer.

**Comment by garg-anuj** [comment]
thanks @Divya10

**Comment by shubhamvashisht** [comment]
I have already added it as a task @garg-anuj

**Pull request merged**
